### ISSUE TITLE
running multi-stream test returns summary of stream total bytes per second value seems off

### ISSUE THREAD

**Issue by eskiipoo** [opensource-3d-p/rperf#1]
Test output:
```
----------
TCP send result over 1.00s | stream: 0
bytes: 1250056 | per second: 1249955.375 | megabytes/second: 1.250
----------
TCP send result over 1.00s | stream: 1
bytes: 1277712 | per second: 1277307.250 | megabytes/second: 1.277
----------
TCP receive result over 1.00s | stream: 0
bytes: 1252952 | per second: 1252644.250 | megabytes/second: 1.253
----------
TCP receive result over 1.00s | stream: 1
bytes: 1279160 | per second: 1279021.250 | megabytes/second: 1.279


----------
TCP send result over 1.00s | stream: 0
bytes: 1270472 | per second: 1270333.750 | megabytes/second: 1.270
----------
TCP send result over 1.00s | stream: 1
bytes: 1280608 | per second: 1280497.750 | megabytes/second: 1.280
----------
TCP receive result over 1.00s | stream: 0
bytes: 1271920 | per second: 1271532.250 | megabytes/second: 1.272
----------
TCP receive result over 1.00s | stream: 1
bytes: 1283504 | per second: 1282977.375 | megabytes/second: 1.283


----------
TCP send result over 1.00s | stream: 0
bytes: 1250056 | per second: 1249949.000 | megabytes/second: 1.250
----------
TCP send result over 1.00s | stream: 1
bytes: 1250056 | per second: 1249945.750 | megabytes/second: 1.250
----------
TCP receive result over 1.05s | stream: 1
bytes: 1247160 | per second: 1188014.000 | megabytes/second: 1.188
----------
TCP receive result over 1.05s | stream: 0
bytes: 1247160 | per second: 1187317.250 | megabytes/second: 1.187


----------
TCP send result over 1.00s | stream: 0
bytes: 1270184 | per second: 1270075.625 | megabytes/second: 1.270
----------
TCP send result over 1.00s | stream: 1
bytes: 1270184 | per second: 1270009.000 | megabytes/second: 1.270
----------
TCP receive result over 1.00s | stream: 0
bytes: 1342872 | per second: 1342705.750 | megabytes/second: 1.343
----------
TCP receive result over 1.00s | stream: 1
bytes: 1334184 | per second: 1329288.125 | megabytes/second: 1.329



----------
TCP send result over 1.00s | stream: 0
bytes: 1274960 | per second: 1274860.000 | megabytes/second: 1.275
----------
TCP send result over 1.00s | stream: 1
bytes: 1269168 | per second: 1269085.375 | megabytes/second: 1.269
----------

----------
TCP send result over 0.05s | stream: 0
bytes: 64000 | per second: 1277847.000 | megabytes/second: 1.278
----------

TCP receive result over 0.97s | stream: 1
bytes: 1203720 | per second: 1240504.750 | megabytes/second: 1.241
[2021-06-18T22:18:24Z INFO  rperf::client] server reported completion of stream 1
----------
TCP receive result over 1.00s | stream: 0
bytes: 1264824 | per second: 1267207.125 | megabytes/second: 1.267
[2021-06-18T22:18:24Z INFO  rperf::client] server reported completion of stream 0


==========
TCP send result over 10.05s | streams: 2
stream-average bytes per second: 1266260.199 | megabytes/second: 1.266
total bytes: 12727456 | per second: 2532520.398 | megabytes/second: 2.533
==========
TCP receive result over 10.07s | streams: 2
stream-average bytes per second: 1263455.403 | megabytes/second: 1.263
total bytes: 12727456 | per second: 2526910.805 | megabytes/second: 2.527
```

I noticed that the summary for total bytes per second value is exactly double of the value of stream-average bytes per second value. 2532520.398 vs 1266260.199.  I also tried to calculate the non rounded time per each send packet and added them together to get a total time.  I then took the total byte and divided by that total time and the value is very close to the stream-average bytes per second.  So I believe that the stream-average bytes per second is correct however, I don't think the total bytes per second is correct. For example the `per second: 2532520.398` does not looks right from this line "total bytes: 12727456 | per second: 2532520.398 | megabytes/second: 2.533"

**Comment by flan** [comment]
The total calculation right now is a direct multiplier, since it seemed like a straightforward way to get an accurate-enough value without needing to account for differences in how long each stream's receive-window lasts (though interpolating each block's average would work, too, but I believe it would come out to the same value).

The idea behind the "total" line is that it shows much much data was exchanged over the real sampling time: assuming you were running five streams for ten seconds, five operations would have run in parallel (so 50 seconds of per-stream time, when summed), but only 10 seconds of "real" time would have elapsed, so dividing the total amount of traffic by 50 seconds doesn't reflect what the link actually transported in that time.

They're two ways of thinking of the same data, with "total" likely being what most people will care about.

I've been unable to figure out how you arrived at those values, though. The only thing that would seem to explain it is if you were using an omit-window of 5s.

Can you provide the command used to invoke the client?

**Comment by eskiipoo** [comment]
I believe this is the command I used
```
rperf -c 10.30.50.10 -b 1250000 -l 32000 -P 2 -t 5
```
So I should divide the total bytes by time. So in this case 12727456/ 5 = 2545491.2, which is close to 2526910.805 but not exact. would that be what you expect?

**Comment by flan** [comment]
Oh, I see the disconnect. I'm showing time across all streams at the top of the final block, which visually clashes with "total" data.

The division isn't exactly by 5.0, but rather the sum of sent or received time (then divided by stream-count, or any other equivalent formula).

It's really just about making the mbps value something that seems meaningfully correct. I expect anyone who's using this data for anything beyond "yeah, this feels right" or "this is way off" reactions will be processing the JSON output in a granular way that's appropriate for their needs.

**Comment by eskiipoo** [comment]
So should this line found in the final summary block be over 5s instead of 10.05s?:
```
TCP send result over 10.05s | streams: 2
```

**Comment by flan** [comment]
The displayed time-value has been changed to something that should be more-intuitive when working with multiple streams: it's now the value of the longest-running stream of the corresponding type.

In the case of test failures, the numbers won't divide nicely by what's shown (for that, average would make more sense), but it should more intuitively match with the reader's expectations.

**Comment by eskiipoo** [comment]
Ok I have tested the latest commit and the time value seem more intuitive now. closing
